### ISSUE TITLE
Camera feed not working in recent versions

### ISSUE THREAD

**Issue by Hless** [zappar-xr/zappar-babylonjs#104]
**Describe the bug**
Camera feed not starting at all in version v0.3.32 and v0.3.32. Tested with babylon v4.2.2, and v5.2.0.

Camera feed is working with version v0.3.31 and babylon v4.2.2, note: this version does not work with babylon v5+

**To Reproduce**
Currently broken in standalone bootstrap example app, when you start the example, nothing will display except the default babylon grey-ish background:
https://github.com/zappar-xr/zappar-babylonjs-image-tracking-standalone-bootstrap

**Expected behavior**
I expect the camera feed to start

**Comment by nyan-left** [comment]
Hi @Hless,

Thanks for the report. Taking a look!

**Comment by nyan-left** [comment]
Fixed with 0.3.34 and updated the example repo 😄

**Comment by Hless** [comment]
Hi @nyan-left ,

That was quick and good news!

I am using the es-6 version of the library (https://www.npmjs.com/package/@zappar/zappar-babylonjs-es6). It seems like that one isn't published yet, will take a look when that one is published to latest version :)

**Comment by nyan-left** [comment]
Hey @Hless,

It'll be up shortly, shall update the thread once it's out!

**Comment by nyan-left** [comment]
The es-6 package has now been deployed:
https://www.npmjs.com/package/@zappar/zappar-babylonjs-es6/v/0.3.34
https://www.npmjs.com/package/@zappar/zappar-babylonjs-es6/v/2.0.0-beta.6
